# -*- coding: utf-8 -*-
"""URK20CS2045 MINI-PROJECT 2022 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bg_r6phuMq1Hg_ZYdizh66RU3nyFxHpaX
"""

# %pip install pyngrok

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/mini-project/

# Commented out IPython magic to ensure Python compatibility.
# %pip install pyqrcode
# %pip install pypng
# %pip install Pillow

from pyngrok import ngrok
import pyqrcode
import png
from PIL import Image
ngrok.set_auth_token("2G39so4QvPGo0hNDbcWzySKeWNz_3YA2zUZ5e9L6SBMYB2AMz")
public_url =  ngrok.connect(5000).public_url
print(public_url)
url = pyqrcode.create(public_url)
img = "qr-code.png"
url.png(img, scale=10)
im=Image.open(img)
im

# !python app.py